theme: jekyll-theme-cayman
title: Open-DIS
description: An open source implementation of the IEEE-1278.1 Distributed Interactive Simulation (DIS) application protocol
google_analytics: UA-108076073-1
github:
  repository_url: https://github.com/open-dis
